### ISSUE TITLE
No Reducer instances for containers

### ISSUE THREAD

**Issue by richsmith92** [ekmett/monoids#2]
In fresh ghci session:

```
ghci> :m Data.Set Data.Monoid.Reducer
ghci> unit () :: Set ()

<interactive>:1:1:
    No instance for (Reducer () (Set ()))
      arising from a use of `unit'
    Possible fix: add an instance declaration for (Reducer () (Set ()))
    In the expression: unit () :: Set ()
    In an equation for `it': it = unit () :: Set ()
ghci> unit () :: [()] -- for comparison
[()]
```

Same for Map and probably other containers. I think you should remove these "#ifdef M_CONTAINERS" lines. I searched in google for "M_CONTAINERS", and this seems to be only in monoids package.

**Comment by richsmith92** [comment]
Sorry for close/reopen. It wasn't a good idea to try github hotkeys by pressing random keys :)

**Comment by ekmett** [comment]
Sounds right. Have you tried the later reducers package?

I need to deprecate monoids.

**Comment by richsmith92** [comment]
On Wed, Nov 23, 2011 at 3:14 AM, Edward A. Kmett <
reply@reply.github.com

> wrote:
> 
> Sounds right. Have you tried the later reducers package?

Thanks, that helps.

**Comment by richsmith92** [comment]
So, do as you wish with the issue, this doesn't matter much since you want to deprecate the package.
